/**
 * tournamentService.ts — Tournament CRUD for VOLK 1303
 *
 * Manages tournament lifecycle: creation, updates, deletion,
 * and participant tracking against the `tournaments` table.
 */

import { supabase } from '../lib/supabase';
import type { TournamentRow, TournamentInsert } from '../types/database';

/**
 * Fetch all tournaments, ordered by creation date (newest first).
 */
export async function fetchTournaments(): Promise<TournamentRow[]> {
  try {
    const { data, error } = await supabase
      .from('tournaments')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('[tournamentService] fetchTournaments error:', error.message);
      return [];
    }

    return (data as TournamentRow[]) ?? [];
  } catch (err) {
    console.error('[tournamentService] fetchTournaments unexpected error:', err);
    return [];
  }
}

/**
 * Fetch a single tournament by its ID.
 */
export async function fetchTournamentById(id: string): Promise<TournamentRow | null> {
  try {
    const { data, error } = await supabase
      .from('tournaments')
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      console.error('[tournamentService] fetchTournamentById error:', error.message);
      return null;
    }

    return data as TournamentRow;
  } catch (err) {
    console.error('[tournamentService] fetchTournamentById unexpected error:', err);
    return null;
  }
}

/**
 * Create a new tournament. The `id` is auto-generated by the DB.
 */
export async function createTournament(
  data: Omit<TournamentInsert, 'id'>
): Promise<TournamentRow | null> {
  try {
    const { data: created, error } = await supabase
      .from('tournaments')
      .insert(data)
      .select()
      .single();

    if (error) {
      console.error('[tournamentService] createTournament error:', error.message);
      return null;
    }

    return created as TournamentRow;
  } catch (err) {
    console.error('[tournamentService] createTournament unexpected error:', err);
    return null;
  }
}

/**
 * Update a tournament with partial data.
 */
export async function updateTournament(
  id: string,
  data: Partial<TournamentRow>
): Promise<TournamentRow | null> {
  try {
    const { data: updated, error } = await supabase
      .from('tournaments')
      .update(data)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      console.error('[tournamentService] updateTournament error:', error.message);
      return null;
    }

    return updated as TournamentRow;
  } catch (err) {
    console.error('[tournamentService] updateTournament unexpected error:', err);
    return null;
  }
}

/**
 * Delete a tournament by ID.
 * Returns true on success, false on failure.
 */
export async function deleteTournament(id: string): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('tournaments')
      .delete()
      .eq('id', id);

    if (error) {
      console.error('[tournamentService] deleteTournament error:', error.message);
      return false;
    }

    return true;
  } catch (err) {
    console.error('[tournamentService] deleteTournament unexpected error:', err);
    return false;
  }
}

/**
 * Increment the participant count of a tournament by 1.
 * Uses a read-then-write pattern since Supabase doesn't support
 * atomic increment without an RPC. If you add a DB function
 * `increment_participants(tournament_id uuid)`, swap to `.rpc()`.
 */
export async function incrementParticipants(
  tournamentId: string
): Promise<TournamentRow | null> {
  try {
    // 1. Read current count
    const { data: current, error: readError } = await supabase
      .from('tournaments')
      .select('participants_count')
      .eq('id', tournamentId)
      .single();

    if (readError || !current) {
      console.error('[tournamentService] incrementParticipants read error:', readError?.message);
      return null;
    }

    const newCount = (current.participants_count ?? 0) + 1;

    // 2. Write new count
    const { data: updated, error: writeError } = await supabase
      .from('tournaments')
      .update({ participants_count: newCount })
      .eq('id', tournamentId)
      .select()
      .single();

    if (writeError) {
      console.error('[tournamentService] incrementParticipants write error:', writeError.message);
      return null;
    }

    return updated as TournamentRow;
  } catch (err) {
    console.error('[tournamentService] incrementParticipants unexpected error:', err);
    return null;
  }
}
